# Generated by Django 4.1.5 on 2023-01-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='from_date',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='to_date',
            field=models.CharField(max_length=20),
        ),
    ]
